# 1. Build-Phase
FROM node:20-alpine AS build
WORKDIR /app

# Abhängigkeiten kopieren und installieren
COPY package*.json ./
RUN npm install

# Quellcode kopieren und Angular-App bauen
COPY . .
RUN npm run build --prod

# 2. Run-Phase mit Nginx
FROM nginx:alpine
# Kopiere den Produktions-Build in den Nginx-Ordner
COPY --from=build /app/dist/birthdayappfrontend /usr/share/nginx/html

# Optional: eigene Nginx-Konfiguration (z. B. für Angular Routen)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Port freigeben
EXPOSE 80

# Nginx im Vordergrund starten
CMD ["nginx", "-g", "daemon off;"]